### PR TITLE
replace IDL, add prev. version as versioned, add current live version…

### PR DESCRIPTION
**Pull request by bowtiedpyro**
Updated the IDL, added the prev. IDL as versioned, also added the new IDL as versioned as was done in the last merge by James. 

If approved - I need to update NPM @Restuta I don't think I have access to do so?

### CODE REVIEW

**Review by Restuta — APPROVED** [review]
LGTM

**Comment by Restuta** [comment]
also invited you to our NPM org

**Comment by bowtiedpyro** [comment]
waiting on a response from NPM - can't get into the account. @Restuta also, since we have made changes to the contract, we should probably repeat this process.

**Comment by Restuta** [comment]
@bowtiedpyro Mithomi said there are no changes from JS world

**Comment by Restuta** [comment]
Regarding NPM - maybe we can try different email

**Comment by bowtiedpyro** [comment]
Got access to my account, but the invite has expired - please resend an invitation to pyro@sharky.fi

**Pull request merged**
